#!/bin/bash

usage() {
    echo "Usage: git rebase-noninteractive COMMIT"
    echo
    echo "Options:"
    echo "  -h --help  Displays this help."
    echo
    echo "Arguments:"
    echo "  COMMIT  The commit to use as the upstream"
    [[ -z $1 ]] && return
    echo
    echo "Description:"
    echo "  Performs an interactive git rebase without the interactivity."
    echo "  Intended usage is to clean up fixup! / squash! commits."
    echo
    echo "Note:"
    echo "  This is still a work in progress. Do not expect it to work."
}

editor=no

while (( $# > 0 )); do
    case "$1" in
        -h|--help)
            usage full
            exit
            ;;
        --editor)
            editor=yes
            ;;
        --)
            shift
            break
            ;;
        -*)
            echo "unknown flag $1" >&2
            usage >&2
            exit 1
            ;;
        *)
            break
    esac
    shift
done

if [[ $editor = yes ]]; then
    # editor mode, verify that we have at least one fixup/squash command
    good=no
    while read -r LINE; do
        if [[ "$LINE" == "fixup " || "$LINE" == "squash " ]]; then
            good=yes
        fi
        printf "%s\n" "$LINE"
    done
    if [[ $good = no ]]; then
        echo "No fixup/squash instructions found; is the commit correct?" >&2
        exit 1
    fi
    exit 0
fi

if (( $# != 1 )); then
    usage >&2
    exit 1
fi

commit=$1

exec git -c core.editor='git-rebase-noninteractive --editor' rebase -i "$commit"
